Runtrack 2: 

Jour 2 - Class en python
La programmation c’est class

By: Khaled METWALLY

Date: 15/09/2022

Introduction de classes

In [15]:
# Class for Point
 
class Point:

    # The init method or constructor
    def __init__(self, x, y):
        self.__x = x
        self.__y = y

    def get_coordinate(self):
        return self.__x,self.__y
    
    def set_coordinate(self,x1,y1):
        self.__x=x1
        self.__y=y1

P1=Point(2,3)

x,y=P1.get_coordinate()
print('x=', x,', y=', y)

x= 2 , y= 3


Job 0
Créez une classe “Personne” avec les attributs “nom”, “prenom”. Ajoutez une méthode “SePresenter()” qui affichera dans le terminal le nom et le prénom de la personne.
Ajoutez aussi un constructeur prenant en paramètres de quoi donner des valeurs initiales aux attributs “nom” et “prenom”. Instanciez plusieurs personnes avec les
valeurs de construction de votre choix et faites appel à la méthode “SePresenter()” afin de vérifier que tout fonctionne correctement. Ajouter un “accesseur” et un “mutateur”
pour chacun des attributs.

In [16]:
# Class with init method

class Personne:
 
    # init method or constructor
    def __init__(self, nom="nom", prenom="prenom"):
        self.nom = nom
        self.prenom = prenom
 
    # Method
    def accesseur_nom(self):
        return print('NOM: ', self.nom)
    
    def mutateur_nom(self):
        self.nom = input("Ajouter votre nom: ")

    def accesseur_prenom(self):
        return print('PRENOM: ', self.prenom)
    
    def mutateur_prenom(self):
        self.prenom = input("Ajouter votre prenom: ")

    def SePresenter(self):
        print('Salut, je suis', self.nom, self.prenom)
 
p0= Personne()
p0.SePresenter()

p1 = Personne("Lombard", "Bruno")
p2 = Personne("Baille", "Roger")

p1.SePresenter()
p2.SePresenter()

p= Personne()
p.mutateur_nom()
p.mutateur_prenom()
p.SePresenter()


Salut, je suis nom prenom
Salut, je suis Lombard Bruno
Salut, je suis Baille Roger


KeyboardInterrupt: Interrupted by user

In [ ]:
p1.accesseur_nom()

NOM:  Lombard


Job 01
Créer une classe “Livre” avec comme attribut un “titre” qu’elle reçoit en paramètre à la construction et une référence vers une classe “Auteur”. Ajouter une méthode “print”
permettant d’afficher dans le terminal le titre du livre. Créer une classe “Auteur” héritant de la classe “Personne” recevant un nom et un prénom en paramètre de construction.
La classe auteur devra posséder une collection de livres nommée "œuvre" en attribut ainsi qu’une méthode “listerOeuvre” affichant dans le terminal la liste des livres écrits
par l’auteur. Ajouter à la classe Auteur une méthode “ecrireUnLivre” prenant en paramètre un titre de livre à écrire et générer une instance de la classe livre avec ce
titre. Ajouter ce nouveau livre à l’oeuvre de l’auteur

In [ ]:
# Class with init method
class Livre:
    # init method or constructor
    def __init__(self, titre="titre"):
        self.titre = titre
  
    # Method
    def printStr(self):
        print('Titre du livre:', self.titre)
 
 # Inherited or Subclass (Note Person in bracket)
class Auteur(Personne):
    # init method or constructor
    def __init__(self, nom, prenom, oeuvre="Around_the_world_in_80_days",list_oeuvre=["Around_the_world_in_80_days"]):
        Personne.__init__(self, nom, prenom)
        self.oeuvre = oeuvre
        self.list_oeuvre = list_oeuvre

    # Method
    def add_oeuvre(self):
        self.oeuvre=input("Ajouter votre une oeuvre: ")
        self.list_oeuvre+=[self.oeuvre]
        return self.list_oeuvre

    def listerOeuvre(self):
        return print(self.list_oeuvre)
        

In [ ]:
M=Auteur('K','M')
#M.add_oeuvre()
M.listerOeuvre()

['Around_the_world_in_80_days', 'yy']


Job 02.718

Créer une classe “Client” héritant de “Personne”, prenant en paramètre un nom et un prenom.
Créez une classe “Bibliotheque” avec comme attributs un nom et un catalogue: une collection de livres ou chaque livre est associé à une quantité (représenté par un nombre entier). Ajoutez les méthodes suivantes :
- acheterLivre: Prenant en paramètre un objet auteur, le nom d’un livre ainsi qu’un nombre entier représentant une quantité. Si le livre existe bien dans l'œuvre de l’auteur, ajouter ce livre au catalogue de la bibliothèque avec la quantité correspondante.
- inventaire: Une méthode qui affiche dans le terminal les titres des livres présents dans le catalogue ainsi que leur quantité.
- louer: Cette méthode reçoit en paramètres une instance d’objet “Client” ainsi que le nom d’un livre. Si le livre existe et est en stock, ajoutez ce livre à la collection de livre du client et tenez à jour la quantité de ce livre dans la bibliothèque.
- rendreLivres: Une méthode qui prend un “Client” en paramètre et qui récupère tous les livres de ce dernier et les ajoute au catalogue de la bibliothèque.
Ajouter à la classe “Client” un attribut collection étant une collection de livres et ajouter la méthode inventaire qui affiche dans le terminal les titres des livres en possession du client.
Ensuite, instanciez des auteurs, faites leurs écrire des livres, créer des bibliothèques, faites les acheter des livres, créez des clients, faites les louer des livres puis utilisez des fonctions d'affichage et montrez le résultat à votre examinateur.

In [ ]:
class Client(Personne):
    # init method or constructor
    def __init__(self, nom, prenom):
        Personne.__init__(self, nom, prenom)

class Bibliotheque:
    # init method or constructor
    def __init__(self, nom="Central_Library", catalogue={}):
        self.nom = nom
        if catalogue is None:       
            self.catalogue = {}
        else:
            self.catalogue = catalogue
        
    
    # Method
    def acheterLivre(self):
        self.oeuvre=input("Ajouter votre une oeuvre: ")
        self.numb=input("Combien d'oeuvre acheter: ")
        
        if self.oeuvre in self.catalogue.keys():
            self.catalogue[self.oeuvre] += self.numb
        else:  
            self.catalogue[self.oeuvre] = self.numb
        return self.catalogue

    def inventaire(self):
        return print(self.catalogue)
    
    def louer(self):
        return print(self.list_oeuvre)

    def rendreLivres(self,Client):
        return print(self.list_oeuvre)

In [ ]:
CMB=Bibliotheque()
CMB.acheterLivre()
CMB.acheterLivre()
CMB.acheterLivre()
CMB.inventaire()

{'KM': '51', 'ND': '6', 'HG': '9', 'MM': '8', 'DD': '7'}


In [ ]:
type(CMB.catalogue)

dict

Job 07.389

Vous allez créer dans ce Job un jeu de puissance 4 sur plateau de taille variable ainsi qu’un algorithme qui sera capable de jouer des coups mesurés.

Commencez par créer une classe “Board” prenant en paramètres de construction deux entiers i et j. Créez un attribut, sous la forme d’un tableau à 2 dimensions, représentant un plateau de jeu en deux dimensions de taille i x j. Ce tableau représente:
- les cases vides par des O
- les jetons jaunes par des J
- les jetons rouges par des R

Créez une méthode “play” qui prend en paramètres un nombre entier ainsi qu’une chaine de caracteres pouvant être “rouge” ou “jaune”. Le nombre entier correspond à la colonne dans laquelle un jeton de jeu est inséré et la couleur correspond à la couleur du joueur jouant ce jeton. Après un coup, tenez à jour votre plateau de jeu en plaçant le jeton le plus bas possible dans la colonne où il a été joué.

Ajouter une méthode “print” affichant dans le terminal l’état du plateau de jeu. 

Implémentez le déroulement d’une partie en demandant aux joueurs humains de jouer à tour de rôle en choisissant la colonne dans laquelle ils souhaitent insérer leurs jetons.

Le premier joueur à aligner 4 jetons de sa couleur gagne la partie et reçoit 100 000
euros.

In [33]:
import numpy as np

# Class with init method

class Board:
 
    # init method or constructor
    def __init__(self, i=6, j=7):
        self.i = i      # number of rows
        self.j = j      # number of columns
        self.board = Board.create_board(self,i,j)
        self.turn=1     # Start with Player 1
        self.gameover=False
    
    # Method
    def create_board(self, i,j):
        #board = np.array((self.i,self.j))
        board =[np.array(['O' for x in range(j)]) for y in range(i)]
        return board
    
    def play(self,col,piece):
        if (self.turn == 1) and (piece =='R') and not(self.gameover):
            #col = int(input("Player 1, Make your Selection(0-6):"))
            #Player 1 will drop a piece on the board
            if self.is_valid_location(col):
                row = self.get_next_open_row(col)
                self.drop_piece(row,col,'R')
                if self.winning_move(self.i,self.j,'R')==True:
                #if self.winning_move(row,col,piece)=='True':
                    print('Game Over Player 1 wins')
                    self.gameover=True
                else:
                    self.turn=2
            else:
                print('Choose another column Player 1 "R":')
         
         #Ask for player 2 input
        elif (self.turn == 2) and (piece =='J') and not(self.gameover):
            #col = int(input("Player 2, Make your Selection(0-6):"))
            #Player 2 will drop a piece on the board
            if self.is_valid_location(col):
                row = self.get_next_open_row(col)
                self.drop_piece(row,col,'J')
                if self.winning_move(self.i,self.j,'J')==True:
                #if self.winning_move(row,col,piece)=='True':
                    print('Game Over Player 2 wins')
                    self.gameover=True
                else:
                    self.turn=1
            else:
                print('Choose another column Player 2 "J":')

    
    def drop_piece(self,row,col,piece):
        self.board[row][col]= piece

    def is_valid_location(self,col):
        #if this condition is true we will let the use drop piece here.
        #if not true that means the col is not vacant
        return self.board[self.i-1][col]=='O'
    
    def get_next_open_row(self,col):
        for r in range(self.i):
            if self.board[r][col]=='O':
                return r

    def winning_move(self, ROW_COUNT, COLUMN_COUNT, piece):
        # Check horizontal locations for win
        for c in range(COLUMN_COUNT-3):
            for r in range(ROW_COUNT):
                if self.board[r][c] == piece and self.board[r][c+1] == piece and self.board[r][c+2] == piece and self.board[r][c+3] == piece:
                    return True
 
        # Check vertical locations for win
        for c in range(COLUMN_COUNT):
            for r in range(ROW_COUNT-3):
                if self.board[r][c] == piece and self.board[r+1][c] == piece and self.board[r+2][c] == piece and self.board[r+3][c] == piece:
                    return True
 
        # Check positively sloped diaganols
        for c in range(COLUMN_COUNT-3):
            for r in range(ROW_COUNT-3):
                if self.board[r][c] == piece and self.board[r+1][c+1] == piece and self.board[r+2][c+2] == piece and self.board[r+3][c+3] == piece:
                    return True
 
        # Check negatively sloped diaganols
        for c in range(COLUMN_COUNT-3):
            for r in range(3, ROW_COUNT):
                if self.board[r][c] == piece and self.board[r-1][c+1] == piece and self.board[r-2][c+2] == piece and self.board[r-3][c+3] == piece:
                    return True

    def print_board(self):
        print(np.flip(self.board,0))
        if(self.gameover=='True'):
            print("Game Over")
     

In [34]:
Connect4=Board()
#dd=Board.create_board(Connect4,10,5)
Connect4.board
Connect4.play(1,'R')
Connect4.play(2,'J')
Connect4.play(1,'R')
Connect4.play(2,'J')
Connect4.play(1,'R')
Connect4.play(2,'J')    # 
Connect4.play(1,'R')
Connect4.play(2,'J')    # 
Connect4.play(1,'R')

Game Over Player 1 wins


In [35]:
Connect4.print_board()

[['O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'R' 'O' 'O' 'O' 'O' 'O']
 ['O' 'R' 'J' 'O' 'O' 'O' 'O']
 ['O' 'R' 'J' 'O' 'O' 'O' 'O']
 ['O' 'R' 'J' 'O' 'O' 'O' 'O']]


In [8]:
import numpy as np

ROW_COUNT = 6
COLUMN_COUNT = 7
 
def create_board():
    board = np.zeros((6,7))
    return board
 
def drop_piece(board,row,col,piece):
    board[row][col]= piece
 
def is_valid_location(board,col):
    #if this condition is true we will let the use drop piece here.
    #if not true that means the col is not vacant
    return board[5][col]==0
 
def get_next_open_row(board,col):
    for r in range(ROW_COUNT):
        if board[r][col]==0:
            return r
     
def print_board(board):
    print(np.flip(board,0))
     
board = create_board()
print_board(board)
game_over = False
turn = 0
 
while not game_over:
    #Ask for player 1 input
    if turn == 0:
        col = int(input("Player 1, Make your Selection(0-6):"))
        #Player 1 will drop a piece on the board
        if is_valid_location(board,col):
            row = get_next_open_row(board,col)
            drop_piece(board,row,col,1)
         
    #Ask for player 2 input
    else:
        col = int(input("Player 2, Make your Selection(0-6):"))
        #Player 2 will drop a piece on the board
        if is_valid_location(board,col):
            row = get_next_open_row(board,col)
            drop_piece(board,row,col,2)
 
    print_board(board)
             
    turn += 1
    turn = turn % 2

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2.

ValueError: invalid literal for int() with base 10: ''

Job 20.085

Créez une classe AI_One. Cette classe devra implémenter une méthode “think” prenant en paramètres un board ainsi qu’une chaine de caracteres pouvant être “rouge” ou
“jaune”. Cette méthode devra retourner le numéro de colonne dans laquelle jouer en tant que joueur de la couleur donnée.

Implémentez le déroulement d’une partie permettant à un joueur de jouer contre AI_One.

Job 54.598

Créez une classe AI_Two identique à la classe AI_One mais insérez-y le code de l’IA d’un
de vos collègues puis implémentez une partie entre ces 2 IAs.